# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-RobotRules-MySQLCache
version:      0.01
version_from: lib/WWW/RobotRules/MySQLCache.pm
installdirs:  site
requires:
    DateTime::Format::Epoch:       0
    DBI:                           0
    LWP::Simple:                   0
    WWW::RobotRules::Parser:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
